server:
  port: 8200

spring:
  profiles:
    active: dev
  application:
    name: LocationService
  cloud: 
    config:
      enabled: true
      uri: http://localhost:8888/
      
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"