spring:
  application:
    name: frontendService
  thymeleaf:
    cache: false
    
eureka:
  instance:
    appname: frontendService
  client:
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
server:
  port: 80
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

#zuul:
#  ignoredServices: "*"
#  routes:
#    BackendService: 
#      path: /danh-muc-dung-chung/**
#      serviceId: backendService