spring:
  application:
    name: LocationService
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost/iPortal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
management:
  endpoints:
    web:
      exposure:
        include: "*"